PRODUCT_VERSION_MAJOR = 19
PRODUCT_VERSION_MINOR = 1

LINEAGE_BUILD_TYPE ?= UNOFFICIAL
LINEAGE_DATE_YEAR := $(shell date -u +%Y)
LINEAGE_DATE_MONTH := $(shell date -u +%m)
LINEAGE_DATE_DAY := $(shell date -u +%d)
LINEAGE_DATE_HOUR := $(shell date -u +%H)
LINEAGE_DATE_MINUTE := $(shell date -u +%M)
LINEAGE_BUILD_DATE_UTC := $(shell date -d '$(LINEAGE_DATE_YEAR)-$(LINEAGE_DATE_MONTH)-$(LINEAGE_DATE_DAY) $(LINEAGE_DATE_HOUR):$(LINEAGE_DATE_MINUTE) UTC' +%s)
LINEAGE_BUILD_DATE := $(LINEAGE_DATE_YEAR)$(LINEAGE_DATE_MONTH)$(LINEAGE_DATE_DAY)-$(LINEAGE_DATE_HOUR)$(LINEAGE_DATE_MINUTE)
TARGET_PRODUCT_SHORT := $(subst lineage_,,$(LINEAGE_BUILD))
LINEAGEVERSION = 19.1

# OFFICIAL_DEVICES
ifeq ($(LINEAGE_BUILD_TYPE), OFFICIAL)
  LIST = $(shell cat vendor/lineage/lineage.devices)
    ifeq ($(filter $(LINEAGE_BUILD), $(LIST)), $(LINEAGE_BUILD))
      IS_OFFICIAL=true
      LINEAGE_BUILD_TYPE := OFFICIAL
    endif
    ifneq ($(IS_OFFICIAL), true)
      LINEAGE_BUILD_TYPE := UNOFFICIAL
      $(error Device is not official "$(LINEAGE_BUILD)")
    endif
endif

LINEAGE_VERSION := $(LINEAGEVERSION)-$(LINEAGE_BUILD)-$(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILD_TYPE)

LINEAGE_MOD_VERSION :=$(ANDROID_VERSION)-$(LINEAGEVERSION)

LINEAGE_DISPLAY_VERSION := LINEAGEEXTENDED-$(LINEAGEVERSION)-$(LINEAGE_BUILD_TYPE)

LINEAGE_DISPLAY_BUILDTYPE := $(LINEAGE_BUILD_TYPE)

LINEAGE_FINGERPRINT := LINEAGEEXTENDED/$(LINEAGE_MOD_VERSION)/$(TARGET_PRODUCT_SHORT)/$(shell date -u +%H%M)